### ISSUE TITLE
Submit to package manager?

### ISSUE THREAD

**Issue by Amparose** [bicarlsen/vintage_relnums#1]
Hey, this looks like it is exactly what I am after. I was disappointed there was no easy way to have relative line numbers like VSCode. Could you submit it to the Package Manager so it is easier to install/update?

https://packagecontrol.io/docs/submitting_a_package

**Comment by bicarlsen** [comment]
Package has been submitted and is awaiting approval.

Thank you for the suggestion.

**Comment by bicarlsen** [comment]
There is also a new setting in ST4 called `relative_line_numbers` for this functionality natively. However, this changes the realtive numbering in modes, not just vintage command mode.

**Comment by Amparose** [comment]
> There is also a new setting in ST4 called `relative_line_numbers` for this functionality natively. However, this changes the realtive numbering in modes, not just vintage command mode.

Yeah I discovered that soon after and it works really well. Also easy to toggle it on/off. I do like having both absolute and relative line numbers showing at once though, which your add-on allows.

**Comment by bicarlsen** [comment]
The package has been added to [Package Control](https://packagecontrol.io/packages/Vintage%20Relative%20Lines).
