### ISSUE TITLE
New tabs always start with the wrong setting

### ISSUE THREAD

**Issue by glubbfreund** [bicarlsen/vintage_relnums#3]
Hi, 

like the plugin. But If I open a new file or tab I always have to change the line numbers to relative (dont use the option for both) with the keybindings. Would it possible to add a setting for the default setting? Thanks in advance.

**Comment by bicarlsen** [comment]
Glad you are finding it useful :)

It will be a bit before I can work on this, but I'll definitely get around to it in the next weeks. Thanks for the suggestion.

**Comment by bicarlsen** [comment]
I added settings menus in [version 0.1.6](https://github.com/bicarlsen/vintage_relnums/releases/tag/0.1.6) to allow you to specify your default settings. You can read more about this in the [README](https://github.com/bicarlsen/vintage_relnums#readme). Give it a try and let me know how it works for you.

**Comment by khoulihan** [comment]
The settings are not picked up for me (in ST4, build 4143). Trying to open the default settings just opens a blank file, I had to check here on the github for the setting names etc.

**Comment by bicarlsen** [comment]
I am quite busy at the moment so likely won't find time to work on this for a while. If anybody would like to contribute, please feel free to issue a PR.
